services:
  customjenkins:
    build: .
    container_name: "jenkins"
    ports:
      - "80:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
